// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: chatpush.proto

package chatpush

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChatPush_Deliver_FullMethodName = "/chatpush.ChatPush/Deliver"
)

// ChatPushClient is the client API for ChatPush service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatPushClient interface {
	Deliver(ctx context.Context, in *DeliveryRequest, opts ...grpc.CallOption) (*DeliveryResponse, error)
}

type chatPushClient struct {
	cc grpc.ClientConnInterface
}

func NewChatPushClient(cc grpc.ClientConnInterface) ChatPushClient {
	return &chatPushClient{cc}
}

func (c *chatPushClient) Deliver(ctx context.Context, in *DeliveryRequest, opts ...grpc.CallOption) (*DeliveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryResponse)
	err := c.cc.Invoke(ctx, ChatPush_Deliver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatPushServer is the server API for ChatPush service.
// All implementations must embed UnimplementedChatPushServer
// for forward compatibility.
type ChatPushServer interface {
	Deliver(context.Context, *DeliveryRequest) (*DeliveryResponse, error)
	mustEmbedUnimplementedChatPushServer()
}

// UnimplementedChatPushServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatPushServer struct{}

func (UnimplementedChatPushServer) Deliver(context.Context, *DeliveryRequest) (*DeliveryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deliver not implemented")
}
func (UnimplementedChatPushServer) mustEmbedUnimplementedChatPushServer() {}
func (UnimplementedChatPushServer) testEmbeddedByValue()                  {}

// UnsafeChatPushServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatPushServer will
// result in compilation errors.
type UnsafeChatPushServer interface {
	mustEmbedUnimplementedChatPushServer()
}

func RegisterChatPushServer(s grpc.ServiceRegistrar, srv ChatPushServer) {
	// If the following call pancis, it indicates UnimplementedChatPushServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatPush_ServiceDesc, srv)
}

func _ChatPush_Deliver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatPushServer).Deliver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatPush_Deliver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatPushServer).Deliver(ctx, req.(*DeliveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatPush_ServiceDesc is the grpc.ServiceDesc for ChatPush service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatPush_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chatpush.ChatPush",
	HandlerType: (*ChatPushServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Deliver",
			Handler:    _ChatPush_Deliver_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chatpush.proto",
}
