// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v4.25.3
// source: chatpush.proto

package chatpush

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeliveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventID       string                 `protobuf:"bytes,1,opt,name=EventID,proto3" json:"EventID,omitempty"`
	MessageID     int64                  `protobuf:"varint,2,opt,name=MessageID,proto3" json:"MessageID,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	CreateTime    int64                  `protobuf:"varint,4,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	FromUserID    uint64                 `protobuf:"varint,5,opt,name=FromUserID,proto3" json:"FromUserID,omitempty"`
	ToUserID      uint64                 `protobuf:"varint,6,opt,name=ToUserID,proto3" json:"ToUserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryRequest) Reset() {
	*x = DeliveryRequest{}
	mi := &file_chatpush_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryRequest) ProtoMessage() {}

func (x *DeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatpush_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryRequest.ProtoReflect.Descriptor instead.
func (*DeliveryRequest) Descriptor() ([]byte, []int) {
	return file_chatpush_proto_rawDescGZIP(), []int{0}
}

func (x *DeliveryRequest) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

func (x *DeliveryRequest) GetMessageID() int64 {
	if x != nil {
		return x.MessageID
	}
	return 0
}

func (x *DeliveryRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DeliveryRequest) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *DeliveryRequest) GetFromUserID() uint64 {
	if x != nil {
		return x.FromUserID
	}
	return 0
}

func (x *DeliveryRequest) GetToUserID() uint64 {
	if x != nil {
		return x.ToUserID
	}
	return 0
}

type DeliveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivered     bool                   `protobuf:"varint,1,opt,name=Delivered,proto3" json:"Delivered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryResponse) Reset() {
	*x = DeliveryResponse{}
	mi := &file_chatpush_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryResponse) ProtoMessage() {}

func (x *DeliveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatpush_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryResponse.ProtoReflect.Descriptor instead.
func (*DeliveryResponse) Descriptor() ([]byte, []int) {
	return file_chatpush_proto_rawDescGZIP(), []int{1}
}

func (x *DeliveryResponse) GetDelivered() bool {
	if x != nil {
		return x.Delivered
	}
	return false
}

var File_chatpush_proto protoreflect.FileDescriptor

var file_chatpush_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x68, 0x61, 0x74, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x63, 0x68, 0x61, 0x74, 0x70, 0x75, 0x73, 0x68, 0x22, 0xbf, 0x01, 0x0a, 0x0f, 0x44,
	0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x46, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x46, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x1a, 0x0a, 0x08, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x30, 0x0a, 0x10,
	0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x65, 0x64, 0x32, 0x4c,
	0x0a, 0x08, 0x43, 0x68, 0x61, 0x74, 0x50, 0x75, 0x73, 0x68, 0x12, 0x40, 0x0a, 0x07, 0x44, 0x65,
	0x6c, 0x69, 0x76, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x70, 0x75, 0x73, 0x68,
	0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x44, 0x65, 0x6c, 0x69,
	0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1e, 0x5a, 0x1c,
	0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x70,
	0x75, 0x73, 0x68, 0x3b, 0x63, 0x68, 0x61, 0x74, 0x70, 0x75, 0x73, 0x68, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chatpush_proto_rawDescOnce sync.Once
	file_chatpush_proto_rawDescData = file_chatpush_proto_rawDesc
)

func file_chatpush_proto_rawDescGZIP() []byte {
	file_chatpush_proto_rawDescOnce.Do(func() {
		file_chatpush_proto_rawDescData = protoimpl.X.CompressGZIP(file_chatpush_proto_rawDescData)
	})
	return file_chatpush_proto_rawDescData
}

var file_chatpush_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chatpush_proto_goTypes = []any{
	(*DeliveryRequest)(nil),  // 0: chatpush.DeliveryRequest
	(*DeliveryResponse)(nil), // 1: chatpush.DeliveryResponse
}
var file_chatpush_proto_depIdxs = []int32{
	0, // 0: chatpush.ChatPush.Deliver:input_type -> chatpush.DeliveryRequest
	1, // 1: chatpush.ChatPush.Deliver:output_type -> chatpush.DeliveryResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chatpush_proto_init() }
func file_chatpush_proto_init() {
	if File_chatpush_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chatpush_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatpush_proto_goTypes,
		DependencyIndexes: file_chatpush_proto_depIdxs,
		MessageInfos:      file_chatpush_proto_msgTypes,
	}.Build()
	File_chatpush_proto = out.File
	file_chatpush_proto_rawDesc = nil
	file_chatpush_proto_goTypes = nil
	file_chatpush_proto_depIdxs = nil
}
